packages:
  - "auth-service"
  - "capability-system"
  - "canvas-engine"
  - "constants/ts"
  - "debug-tools/ts"
  - "dynamodb-service"
  - "nats-auth-callout-service"
  - "nats-service/ts"
  - "prosemirror"
  - "ui-kit"
