services:
    lixpi-go-quality-runner:
        extends:
            file: ./dev-tools/code-quality/runner-compose/go-quality.base.yml
            service: go-quality-runner-base
        volumes:
            - ./services/nats/go.mod:/usr/src/manifests/nats/go.mod:cached
            - ./services/nats/go.sum:/usr/src/manifests/nats/go.sum:cached
            - ./services/nats/cmd:/usr/src/service/nats/cmd:cached
            - ./services/nats/internal:/usr/src/service/nats/internal:cached
            - ./services/nats/nats-server.conf:/usr/src/service/nats/nats-server.conf:ro,cached
            - ./services/caddy/go.mod:/usr/src/manifests/caddy/go.mod:cached
            - ./services/caddy/go.sum:/usr/src/manifests/caddy/go.sum:cached
            - ./services/caddy/cmd:/usr/src/service/caddy/cmd:cached
            - ./services/caddy/internal:/usr/src/service/caddy/internal:cached

volumes:
    go-quality-runner-module-cache:
    go-quality-runner-build-cache:
    go-quality-runner-lint-cache:
