name: lixpi-versions-registry

services:
    versions-registry:
        extends:
            file: dev-tools/versions-registry/runner-compose/versions-registry.base.yml
            service: versions-registry-base
        image: node:24.21.0-alpine
        volumes:
            - .:/workspace
    versions-registry-update:
        extends:
            file: dev-tools/versions-registry/runner-compose/versions-registry.base.yml
            service: versions-registry-update-base
        image: node:24.21.0-alpine
        volumes:
            - .:/workspace
