services:
    lixpi-config-utils:
        extends:
            file: ./dev-tools/config-utils/runner-compose/config-utils.base.yml
            service: config-utils-base
        user: "${LOCAL_UID:-0}:${LOCAL_GID:-0}"
        volumes:
            - .:/workspace
            - ./dev-tools/config-utils/setup-env.ts:/usr/src/config-utils/repository/setup-env.ts:ro,cached
            - ./dev-tools/config-utils/templates:/usr/src/config-utils/repository/templates:ro,cached
