services:
    lixpi-go-quality-runner:
        extends:
            file: ./dev-tools/code-quality/runner-compose/go-quality.base.yml
            service: go-quality-runner-base
        volumes:
            - ./dev-tools/code-quality/go-quality-runner/go.mod:/usr/src/manifests/go-quality-tools/go.mod:cached
            - ./dev-tools/code-quality/go-quality-runner/go.sum:/usr/src/manifests/go-quality-tools/go.sum:cached
            - ./dev-tools/code-quality/go-quality-runner/source-conventions.go:/usr/src/service/go-quality-tools/source-conventions.go:cached
            - ./dev-tools/code-quality/go-quality-runner/cmd:/usr/src/service/go-quality-tools/cmd:cached
            - ./dev-tools/code-quality/go-quality-runner/internal:/usr/src/service/go-quality-tools/internal:cached
            - ./services/nats/go.mod:/usr/src/manifests/nats/go.mod:cached
            - ./services/nats/go.sum:/usr/src/manifests/nats/go.sum:cached
            - ./services/nats/cmd:/usr/src/service/nats/cmd:cached
            - ./services/nats/internal:/usr/src/service/nats/internal:cached
            - ./services/nats/nats-server.conf:/usr/src/service/nats/nats-server.conf:ro,cached
            - ./services/caddy/go.mod:/usr/src/manifests/caddy/go.mod:cached
            - ./services/caddy/go.sum:/usr/src/manifests/caddy/go.sum:cached
            - ./services/caddy/cmd:/usr/src/service/caddy/cmd:cached
            - ./services/caddy/internal:/usr/src/service/caddy/internal:cached

volumes:
    go-quality-runner-module-cache:
    go-quality-runner-build-cache:
    go-quality-runner-lint-cache:
