package conventions

import (
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"testing"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/analysistest"
)

func TestResolvedSymbolsAndErrorContracts(t *testing.T) {
	directory, cleanup, err := analysistest.WriteFiles(map[string]string{
		"example/symbols.go": `package example
import (
    output "fmt"
    legacy "log"
    "log/slog"
    "io"
)
func prohibited(logger *legacy.Logger) {
    output.Println("message") // want "prohibited-symbol"
    _ = output.Printf // want "prohibited-symbol"
    legacy.Print("message") // want "prohibited-symbol"
    logger.Fatal("message") // want "prohibited-symbol"
    _ = (*legacy.Logger).Printf // want "prohibited-symbol"
    print("message") // want "prohibited-symbol"
    println("message") // want "prohibited-symbol"
    panic("expected failure") // want "prohibited-symbol"
}
type formatter struct{}
func (formatter) Printf(string, ...any) {}
func (formatter) Errorf(string, ...any) error { return nil }
func unrelatedSymbols() {
    fmt := formatter{}
    fmt.Printf("allowed")
    _ = fmt.Errorf("failed to read")
    panic := func(any) {}
    panic("allowed")
    print := func(any) {}
    print("allowed")
    println := func(any) {}
    println("allowed")
    _, _ = output.Fprintf(io.Discard, "explicit output")
    slog.Info("structured output")
    _ = "fmt.Printf and panic in strings are not Go calls"
}
func unreachable() {
    //lixpi:allow-panic validation rejects this branch before dispatch.
    panic("unreachable")
}
`,
		"example/errors.go": `package example
import (
    failure "errors"
    output "fmt"
    text "strings"
)
const badMessage = "failed " + "to read"
func messages(err error) {
    _ = failure.New(badMessage) // want "error-message-step"
    _ = output.Errorf("example: read: %w", err) // want "error-message-step"
    _ = output.Errorf("unable to read: %w", err) // want "error-message-step"
    _ = failure.New("could not read") // want "error-message-step"
    _ = failure.New("error reading") // want "error-message-step"
    _ = failure.New("failedness is not a redundant prefix")
    _ = failure.New("errors remain available")
    _ = failure.New("record absent")
    _ = output.Errorf("read record: %w", err)
    _ = text.Contains(err.Error(), "missing") // want "error-text-match"
    _ = (err.Error()) == "missing" // want "error-text-match"
    switch (err.Error()) { // want "error-text-match"
    case "missing":
    }
    _ = failure.Is(err, failure.New("missing"))
    _ = output.Sprintf("error was %s", err.Error())
}
type counter struct{}
func (counter) Error() int { return 1 }
type matcher struct{}
func (matcher) Contains(string, string) bool { return false }
func nonErrorMethod(err error) {
    _ = (counter{}).Error() == 1
    strings := matcher{}
    _ = strings.Contains(err.Error(), "allowed custom operation")
}
`,
		"example/dot.go": `package example
import . "fmt"
func dotImports(err error) {
    Println("message") // want "prohibited-symbol"
    _ = Errorf("failed to read: %w", err) // want "error-message-step"
}
`,
		"example/contracts_test.go": `package example
import "strings"
func exactResponseContract(err error) bool {
    return strings.Contains(err.Error(), "response code") || err.Error() == "response code"
}
`,
		"example/generated.go": `// Code generated by fixture. DO NOT EDIT.
package example
import "fmt"
func generated() { fmt.Println("generated output") }
`,
	})
	if err != nil {
		t.Fatal(err)
	}

	t.Cleanup(cleanup)
	analysistest.Run(t, directory, New(), "example")
}

func TestErrorMessageWordBoundaries(t *testing.T) {
	for _, message := range []string{"failedness", "errors", "could nothing", "unable tool", "read record: %w"} {
		t.Run(message, func(t *testing.T) {
			if got := redundantErrorMessageText(message, "example"); got != "" {
				t.Errorf("valid message %q reported as %s", message, got)
			}
		})
	}
}

func TestPanicExceptions(t *testing.T) {
	for _, test := range []struct {
		name   string
		body   string
		issues int
	}{
		{"documented", "//lixpi:allow-panic validation rejects this branch.\npanic(1)", 0},
		{"missing reason", "//lixpi:allow-panic\npanic(1)", 2},
		{"detached", "//lixpi:allow-panic validation rejects this branch.\n\npanic(1)", 2},
		{"shadowed", "panic := func(any) {}\n//lixpi:allow-panic not a builtin.\npanic(1)", 1},
		{"local exception", "//lixpi:allow-panic validation rejects this branch.\npanic(1)\npanic(2)", 1},
	} {
		t.Run(test.name, func(t *testing.T) {
			fileSet := token.NewFileSet()

			file, err := parser.ParseFile(fileSet, "example.go", "package example\nfunc example() {\n"+test.body+"\n}", parser.ParseComments)
			if err != nil {
				t.Fatal(err)
			}

			info := &types.Info{Uses: map[*ast.Ident]types.Object{}}
			configuration := &types.Config{}

			pkg, err := configuration.Check("example", fileSet, []*ast.File{file}, info)
			if err != nil {
				t.Fatal(err)
			}

			var diagnostics []analysis.Diagnostic

			_, err = run(&analysis.Pass{
				Fset:      fileSet,
				Files:     []*ast.File{file},
				Pkg:       pkg,
				TypesInfo: info,
				Report:    func(diagnostic analysis.Diagnostic) { diagnostics = append(diagnostics, diagnostic) },
			})
			if err != nil {
				t.Fatal(err)
			}

			if len(diagnostics) != test.issues {
				t.Errorf("got %d diagnostics, want %d: %v", len(diagnostics), test.issues, diagnostics)
			}
		})
	}
}
