packages:
  - "packages/lixpi/capability-system"
  - "packages/lixpi/canvas-engine"
  - "packages/lixpi/constants/ts"
  - "packages/lixpi/debug-tools/ts"
  - "packages/lixpi/nats-service/ts"
  - "packages/lixpi/prosemirror"

allowBuilds:
  "@parcel/watcher": true
  browser-tabs-lock: true
  esbuild: true
  svelte-preprocess: true
